vendor_remove_dirs += \

vendor_remove_files += \
	customize/resource/allapplication.xml \
	customize/resource/CU_bootup_animation.zip \
	customize/resource/CU_bootup_music.mp3 \
	customize/resource/CU_shutdown_animation.zip \
	customize/resource/CU_shutdown_music.mp3 \
	customize/resource/hTC_bootup.zip \
	customize/resource/hTC_downanimation.zip \
	customize/resource/HTC_Sense5_Boot.mp3 \
	customize/resource/icon_launcher_active_sync.png \
	customize/resource/icon_launcher_gmail.png \
	customize/resource/icon_launcher_hotmail.png \
	customize/resource/icon_launcher_mail.png \
	customize/resource/icon_launcher_outlook.png \
	customize/resource/icon_launcher_yahoo.png \
	customize/resource/package_mapping.xml \
	customize/resource/quicklaunch.xml \
	customize/resource/rp_ac_no_nfc.png \
	customize/resource/rp_ac_with_nfc.png \
	customize/resource/rp_ce_0560_i.png \
	customize/resource/rp_ce_0560.png \
	customize/resource/rp_ce_0678_i.png \
	customize/resource/rp_ce_0678.png \
	customize/resource/rp_ce_0682_i.png \
	customize/resource/rp_ce_0682.png \
	customize/resource/rp_ce_0700_i.png \
	customize/resource/rp_ce_0700.png \
	customize/resource/rp_ce_2200_i.png \
	customize/resource/rp_ce_2200.png \
	customize/resource/rp_eac.png \
	customize/resource/rp_pct.png \
	customize/resource/rp_rcm.png \
	customize/resource/s1576efac.jpg \
	customize/resource/s2dcca705.jpg \
	customize/resource/s4027c8b2.jpg \
	customize/resource/s43a4ec7b.jpg \
	customize/resource/s4add27e3.jpg \
	customize/resource/s4d5e5f0e.jpg \
	ustomize/resource/s6088696a.jpg \
	customize/resource/s66a3ac14.jpg \
	customize/resource/s966eeef.jpg \
	customize/resource/s980f4135.jpg \
	customize/resource/saaa5ab11.jpg \
	customize/resource/sb730969d.jpg \
	customize/resource/sbd5dc6f8.jpg \
	customize/resource/sbee497ce.jpg \
	customize/resource/sc16062fb.jpg \
	customize/resource/sc8a1ff6b.jpg \
	customize/resource/sd32a3a14.jpg \
	customize/resource/sfac50f3a.jpg \
	customize/resource/wallpapers_00.jpg \
	customize/resource/wallpapers_01.jpg \
	customize/resource/wallpapers_02.jpg \
	customize/resource/wallpapers_03.jpg \
	customize/resource/wallpapers_04.jpg \
	customize/resource/wallpapers_05.jpg \
	customize/resource/wallpapers_06.jpg \
	customize/resource/wallpapers_07.jpg \
	customize/resource/wallpapers_08.jpg \
	customize/resource/wallpapers_09.jpg \
	customize/resource/wallpapers_10.jpg \
	customize/resource/wallpapers_11.jpg \
	customize/resource/wallpapers_12.jpg \
	customize/resource/wallpapers_13.jpg \
	customize/resource/wallpapers_14.jpg \
	customize/resource/wallpapers_15.jpg \
	customize/resource/wallpapers_16.jpg \
	customize/resource/wallpapers_17.jpg
